server:
  port: 9090

spring:
  application:
    name: qushift
  profiles:
    active: local
  webflux:
    base-path: /api

logging:
  level:
    org:
      springframework:
        web: DEBUG
#        hibernate: INFO