FROM node:16.18.0
WORKDIR /app

ENV NODE_ENV production

COPY /public ./public

# Set mode "standalone" in file "next.config.js"
COPY /.next/standalone ./
COPY /.next/static ./.next/static

EXPOSE 4000

ENV PORT 4000

CMD ["node", "server.js"]